### ISSUE TITLE
User should be able to upload hours

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#10]
![all users upload payroll hours panel](https://cloud.githubusercontent.com/assets/11021008/11648169/08b1b3ba-9d3f-11e5-8016-387fc895906b.png)

See workflow #1

This functionality will require us to figure out what would be the best gem to use that would give us the ability to upload CSV files. #12

If the user is authorized to upload hours for more than one location, or the user is an admin, we will have to include a means for them to choose which store location they will be uploading hours for. Their choice should be limited to one location per upload. They should be prompted to choose a location every time so they don't inadvertently upload hours for the wrong location, i.e. their choice should not be persisted.

**Comment by mkwiatkowski** [comment]
I think a simple select box with the list of locations available to a given user can work here. Include that on your mockup.

**Comment by mkwiatkowski** [comment]
Will users be able to download previously uploaded files? Or is it only a one-way operation?

**Comment by Mei152** [comment]
The mockup has been updated to include a location selection list.

You bring up a good point about users being able to download previously uploaded files. I think this should be split off into its own topic/set of issues. 

The point of this app is to store uploaded data for later consumption. My first thought was that this would primarily be done through a web API, but providing for simple retrieval of data through file download capability makes a lot of sense. We will have to address authorization for this functionality too.

**Comment by Mei152** [comment]
The mockup has been updated to include a location selection list.

You bring up a good point about users being able to download previously uploaded files. I think this should be split off into its own topic/set of issues.

The point of this app is to store uploaded data for later consumption. My first thought was that this would primarily be done through a web API, but providing for simple retrieval of data through file download capability makes a lot of sense. We will have to address authorization for this functionality too.

**Comment by mkwiatkowski** [comment]
A select box is a standard HTML element you may want to use: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select I think it's OK to show it even when the user can't change it because it reassures her that upload is for her location. If you add attribute `disabled` to the select box the user won't be able to change the value, but still see it: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_disabled

> providing for simple retrieval of data through file download capability makes a lot of sense

Yeah, so then you probably want a "download" link in this table, probably next to "uploaded". And the whole feature needs a new ticket. It's OK for one mockup to be referenced by multiple issues. The mockup usually shows the end result, while different issues can implement parts of it.

**Comment by Mei152** [comment]
closed by commit e9412e50e3b5be2d0a46db653b28bad245933c25

residual discussion point about admin being able to download time records moved to new issue #32

**Comment by Mei152** [comment]
closed by commit e9412e5

residual discussion point about admin being able to download time records moved to new issue #32
