### ISSUE TITLE
Add unique constraint on UploadedFile

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#36]
Add unique constraint on UploadedFile for time period & location combination.

**Comment by Mei152** [comment]
Not sure this migration 59a8432524e4ced605a54d1e5a92d9b15820df20 had the intended outcome. The index does appear in pgAdmin under indexes, and probably will serve to prevent duplicates. Does it matter that it does not show up in pgAdmin under constraints? From messing with pgAdmin, it looks like you can create unique constraints based on an index, which leads me to believe that they aren't  the same thing (well, actually I already knew that). You can also create unique constraints without an index, which is what I figured we really wanted, but I couldn't find anything on the web on how write a rails migration that implements an actual index free constraint on the db.

**Comment by mkwiatkowski** [comment]
Functionally the effect is the same, because when you create a constraint the database will automatically make an index anyway. From the docs at http://www.postgresql.org/docs/9.5/static/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS :

> Adding a unique constraint will automatically create a unique B-tree index on the column or group of columns listed in the constraint.

Also the best way is to experiment. Simply try to add two uploaded file records with the same `location_id` and `time_period_start_date` and see what happens.

**Comment by Mei152** [comment]
It does work. I need to implement a flash message specific to the validation error so the user (admin) is not left wondering exactly what went wrong. There is probably a way to prevent a user from even attempting to do this through limiting choices based on what is already in the db. Lot's of front end stuff could be done.
