### ISSUE TITLE
Fix password update validation problem

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#44]
I can't figure this out:

in controller
  `if @user.update_attributes(user_params)`
    and
  `def user_params`
     `params.require(:user).permit(:email, :role, :location_id)`
  `end`

in model"
  `validates :password, presence: true`

update_attributes will fail validation even though password is not included in the attributes being updated. Everything I've read on the web says that update_attributes only attempts to update the attributes passed to it as a hash. If this is the case, why is it passing a nil password to to validation? Maybe I am misunderstanding how validations work. I figured the validation for password would not be called unless the attribute was deliberately being acted on.

**Comment by mkwiatkowski** [comment]
Since you are using devise you can use `update_without_password` method on the`User` model. It's not strictly necessary in this particular case, although it may be more clear to the reader of the code.

Validations _always_ run on a model unless they are conditional (e.g. with `on: :create` or similar).

As to the validation, you don't need to setup validation on `password` since you are using the `validatable` module of devise:

```ruby
devise :database_authenticatable,
         :recoverable, :trackable, :validatable
```

You can see the validations added by the `validatable` module in the source: https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb

**Comment by Mei152** [comment]
I did as you suggested, and removed the redundant password validation from the model, and used update_without_password in the controller. This was done a while ago, and, honestly, I cant find the commit within which it was done. I will be more careful going forward.

**Comment by mkwiatkowski** [comment]
No problem, here's the commit where you changed it: 2b8a37445e71d65e8ebfeb25bff8ea0b411f2be0
