### ISSUE TITLE
Provide functionality to deal with files left in "pending" validation status. 

### ISSUE THREAD

**Issue by Mei152** [Mei152/hours_import#58]
Users should not be able to navigate links, such as home, logout, etc.., while engaged in the file validation process. There should be no way to exit the process that would leave a file in "pending" validation status. The end result of the process should leave the file in "accepted" status, or delete the file.

**Comment by mkwiatkowski** [comment]
Hmm, interesting idea, although you can't really assume this situation will never arise. There are more situations that you don't have control over:

- user closes the browser window
- user's computer crashes
- user's Internet connection is lost

I think it's better to think of a solution to "pending" files, because even if rare those situations can occur.

**Comment by Mei152** [comment]
You have a very good point.  Not only should a user be able to resume the validation/rejection process if disconnected, or if they exit the process, but also the app needs to prevent a new file from being uploaded until the current file is seen through the end of validation.

**Comment by Mei152** [comment]
Everything appears to work. I hope I didn't miss something. Implementing this was intimidating at first, but I was shocked at how little code it actually required. I guess that is the power of rails.
